### ISSUE TITLE
Improve Landing Page Design for Better User Engagement

### ISSUE THREAD

**Issue by atharvbarge04** [atharvbarge04/Landing-page#1]
### Description
The current landing page of the application could use enhancements to make it more visually appealing and user-friendly. The goal is to improve user engagement and retention by creating a more attractive layout and user interface.

### Proposed Changes
1. **Visual Design:**
   - Update color scheme and typography to make the page more vibrant and welcoming.
   - Incorporate high-quality images or graphics that represent the application’s features.

2. **Layout:**
   - Redesign the layout to improve navigation and flow.
   - Add sections for key features, testimonials, and calls to action.

3. **User Experience:**
   - Ensure the landing page is responsive and mobile-friendly.
   - Improve loading speed by optimizing images and reducing unnecessary content.

### Expected Behavior
The new landing page should provide a more engaging experience for users, encouraging them to explore the application further.

### Additional Context
Feel free to check other successful landing pages for inspiration. Collaboration and design suggestions are welcome!

**Label:** #Hacktoberfest

**Comment by adhirajpawar** [comment]
Hello!  @atharvbarge04 👋
I noticed this issue and I would love to contribute to it. Could you please assign it to me, or let me know if there's anything specific you'd like me to focus on? I'm looking forward to helping out!

**Comment by atharvbarge04** [comment]
Hi! @adhirajpawar 👋

Thank you for your interest in contributing to this issue! I would love to assign it to you. Please feel free to focus on making the landing page more visually appealing and user-friendly.

**Comment by Bucksmon** [comment]
Hey @atharvbarge04 

I'd like to propose a visual enhancement through a simple CSS transition. While I don't yet have the experience to make pull requests on GitHub, I’ve added a small code snippet below to give you an idea of my suggestion:
```css
/*=============== Underline on hover animation ===============*/
.nav__link {
    position: relative; /* To position the line under the "Home", "Product" and other tabs. */
}

.nav__link::after {
    content: '';
    position: absolute;
    width: 0;
    height: 2px;
    background-color: var(--white-color); /* White colored underline */
    bottom: -10px;
    left: 0; /* Starts the line from left */
    transition: width 0.3s ease;
}

.nav__link:hover::after {
    width: 100%; /* Makes the line visible on hover */
}
```

This adds a simple hover animation using basic CSS, which could make the navigation more visually appealing. Additionally, I’d suggest considering animated icons for "Home", "Specs", and the other nav-bar options to further enhance the user experience.
Thanks for your time.
